### ISSUE TITLE
Setting up a Group's Reroutes [documenation]

### ISSUE THREAD

**Issue by wyrde** [pythongosssss/ComfyUI#2]
When setting up a group for conversion into a node, it is important to have **reroute** nodes for every item going into the group and out of it. It isn't enough that the nodes in the group are connected, the reroutes have to be present as well.

![2023-04-28 09_14_25-ComfyUI — Mozilla Firefox](https://user-images.githubusercontent.com/9657443/235158544-926e2c76-78e6-4df3-a39f-85224f7d71fa.png)

![2023-04-28 09_16_07-ComfyUI — Mozilla Firefox](https://user-images.githubusercontent.com/9657443/235158673-edc88b7b-a1bc-43e0-8bd8-4688acc301be.png)

**Comment by pythongosssss** [comment]
Any internally unconnected inputs/outputs will be treated as inputs/outputs to the group
e.g. in your screenshot the KSampler output LATENT shouldnt require a reroute as it isnt connected to anything else internally.
The MODEL, CONDITIONING etc are all connected and so do need the reroute so they have an empty output

Hopefully that makes sense

**Comment by wyrde** [comment]
That makes sense.

~~We have to be careful of how many reroutes are in a group, too. Adding extra to untangle the noodles causes problems.~~ Fixed!

**Comment by wyrde** [comment]
Adding documentation:

Right Click on a reroute's or node's "dot" to rename it.

![rename 01](https://user-images.githubusercontent.com/9657443/235319487-c72bda90-ad89-4a75-a54c-b501ddd24bca.png)
![rename 02](https://user-images.githubusercontent.com/9657443/235319489-d51a336f-e52d-42f9-af3f-028df6f5fb62.png)
![rename 03](https://user-images.githubusercontent.com/9657443/235319492-9380c1e8-46a5-4c37-897f-fc4beceffed0.png)
![rename 04](https://user-images.githubusercontent.com/9657443/235319497-dcb7d332-bd72-4a43-bdd1-305baca8b7cf.png)
![rename 05](https://user-images.githubusercontent.com/9657443/235319500-7db9fa7a-6353-4099-a45a-338c9abb22b6.png)
![rename 06](https://user-images.githubusercontent.com/9657443/235319504-cf03312f-d3af-4671-82ee-deddf9f8e4c1.png)
![rename 07](https://user-images.githubusercontent.com/9657443/235319510-0b56bea1-b98f-4932-8a55-9fc86e88d49d.png)
![rename 08](https://user-images.githubusercontent.com/9657443/235319513-d160ee7d-abf3-47d7-b2f4-55f75e9e905d.png)
![rename 09](https://user-images.githubusercontent.com/9657443/235319516-6bff6900-262c-43ad-b1a5-57cb5e4fa1ad.png)
![rename 11](https://user-images.githubusercontent.com/9657443/235319519-efdb1523-475f-439c-be28-2e60bfaf9efa.png)
![rename 13](https://user-images.githubusercontent.com/9657443/235319536-2235f43a-689c-4947-97d4-0da64e5e100e.png)
![rename 14](https://user-images.githubusercontent.com/9657443/235319539-8d4431f8-fdbd-42cf-9dec-747a3d4f7935.png)
![rename 15](https://user-images.githubusercontent.com/9657443/235319540-ba3514d8-e297-4f78-94df-3bf93d7918a4.png)

The change is cosmetic only and does not alter the data type.
