### ISSUE TITLE
KSampler's Seed Input reappers as widget

### ISSUE THREAD

**Issue by wyrde** [pythongosssss/ComfyUI#3]
With a KSampler with a seed input connected to INT reroute, after converting to nodes and back, a seed widget appeared.

Initial KSampler and other nodes
![2023-04-28 09_37_41-ComfyUI — Mozilla Firefox](https://user-images.githubusercontent.com/9657443/235164202-70e535ae-98e3-4fff-b6ec-676d8dc3576c.png)

Adding group
![2023-04-28 09_39_14-ComfyUI — Mozilla Firefox](https://user-images.githubusercontent.com/9657443/235164276-9e0f51c0-2560-4403-b5be-edc9c381052b.png)

converted to node

converted to nodes
![2023-04-28 09_41_27-ComfyUI — Mozilla Firefox](https://user-images.githubusercontent.com/9657443/235164350-5f4cf43f-dc31-4254-b1b4-fc22c04a0aa5.png)

Now there are two seeds.

**Comment by wyrde** [comment]
and now there is three . . . 
![2023-04-28 10_08_18-ComfyUI — Mozilla Firefox](https://user-images.githubusercontent.com/9657443/235170469-385452cc-b5d2-473b-b641-5815380a0ce8.png)

current workflow

[groupnodetest05.zip](https://github.com/pythongosssss/ComfyUI/files/11354287/groupnodetest05.zip)

**Comment by wyrde** [comment]
![2023-04-29 10_11_39-ComfyUI — Mozilla Firefox](https://user-images.githubusercontent.com/9657443/235307345-fe737885-36df-45b5-9767-ac25cdb63287.png)

It appears to be cosmetic. At least, changing values in the widgets doesn't cause a cached node to re-run when queuing workflow.

**Comment by pythongosssss** [comment]
This should be fixed

**Comment by wyrde** [comment]
![2023-04-29 14_41_12-ComfyUI — Mozilla Firefox](https://user-images.githubusercontent.com/9657443/235319022-462c1f0d-ff24-4570-8e42-90b032846b92.png)

Noticed it was fixed while testing the reroute renames. Awesome!
