### ISSUE TITLE
order of inputs/outputs on group node

### ISSUE THREAD

**Issue by wyrde** [pythongosssss/ComfyUI#5]
is there anything that determines the order of input/outputs on the group node?

It seems to be rather random, especially with conditioning.

**Comment by pythongosssss** [comment]
They are added by node in node execution order, then in the normal node order

I could try adding right click -> move up/down onto the inputs
I attempted this with the widgets and it didnt go well

**Comment by wyrde** [comment]
Conditioning worries me the most, because there's no way to tell which is the positive or negative prompt.

**Comment by pythongosssss** [comment]
Pushed an update. You should be able to rename the node/reroute outputs/inputs to make it clear what's what

![image](https://user-images.githubusercontent.com/125205205/235311162-4823e137-d8b2-4da8-81aa-0f5b63397c7b.png)

![image](https://user-images.githubusercontent.com/125205205/235311204-6ec2f497-7d3d-4dbc-bfb4-4f5c146ffde9.png)

**Comment by wyrde** [comment]
Sweet!

![2023-04-29 14_38_11-ComfyUI — Mozilla Firefox](https://user-images.githubusercontent.com/9657443/235318949-e9909689-2550-44fe-8d3c-4c873d9c39a9.png)
