### ISSUE TITLE
TypeError: node.outputs is undefined

### ISSUE THREAD

**Issue by wyrde** [pythongosssss/ComfyUI#6]
Noticed that a workflow .json load or refresh (F5) caused a `TypeError: node.outputs is undefined` error

Pop up:
```
TypeError: node.outputs is undefined

registerCustomNodes/RerouteNode/this.onConnectionsChange@http://127.0.0.1:9288/extensions/core/rerouteNode.js:61:9
LGraphNode.prototype.configure@http://127.0.0.1:9288/lib/litegraph.core.js:2477:11
LGraph.prototype.configure@http://127.0.0.1:9288/lib/litegraph.core.js:2218:26
loadGraphData@http://127.0.0.1:9288/scripts/app.js:1013:15
setup@http://127.0.0.1:9288/scripts/app.js:879:10

This may be due to the following script:
/extensions/core/rerouteNode.js
Queue size: 0
Extra options
```

firefox console
```
Uncaught TypeError: start_node.outputs is undefined
    drawConnections http://127.0.0.1:9288/lib/litegraph.core.js:9262
    drawBackCanvas http://127.0.0.1:9288/lib/litegraph.core.js:8344
    draw http://127.0.0.1:9288/lib/litegraph.core.js:7668
    renderFrame http://127.0.0.1:9288/lib/litegraph.core.js:5731
litegraph.core.js:9262:34
Uncaught TypeError: start_node.outputs is undefined
    drawConnections http://127.0.0.1:9288/lib/litegraph.core.js:9262
    drawBackCanvas http://127.0.0.1:9288/lib/litegraph.core.js:8344
    draw http://127.0.0.1:9288/lib/litegraph.core.js:7668
    resizeCanvas http://127.0.0.1:9288/scripts/app.js:863
```
Reproduce:
* Load workflow json  
[groupnodes-20230429-07.zip](https://github.com/pythongosssss/ComfyUI/files/11360084/groupnodes-20230429-07.zip)
* convert the group to nodes
* F5

Includes older workflows which have groups converted into nodes

**Comment by pythongosssss** [comment]
I've had to rewrite the reroute node in order to get primitive+reroute to work.
Would you be able to switch to a different branch `group-plus-rerouteprimitive`, I don't get any errors on this workflow with that branch (and everything looks like its working, but I can't run that workflow 🫠)

That branch has the group node changes merged with the primitive reroutes, so you shouldnt need to use the int_O node to connect anymore

**Comment by pythongosssss** [comment]
Maybe hold off testing that for a bit 🙈
![image](https://user-images.githubusercontent.com/125205205/235630365-156d7db6-307a-459d-a992-a6c4ea210130.png)

**Comment by wyrde** [comment]
Heh

Starting with this workflow: 
[group+reroute 20230503-01.zip](https://github.com/pythongosssss/ComfyUI/files/11391805/group%2Breroute.20230503-01.zip)

![group+reroute 01](https://user-images.githubusercontent.com/9657443/236069765-3f4dea66-54d7-4a19-b90b-643ccc0e22b2.png)

![group+reroute 02](https://user-images.githubusercontent.com/9657443/236069797-00b95b57-9d03-40da-acd2-1d3aeb37275f.png)
![group+reroute 03](https://user-images.githubusercontent.com/9657443/236069825-fb6bf6ba-2d06-47c8-aab8-8d4ad7416b18.png)
![group+reroute 04](https://user-images.githubusercontent.com/9657443/236069850-b74022ac-ea9b-4218-ba14-eec2808ff108.png)
![group+reroute 05](https://user-images.githubusercontent.com/9657443/236069878-d42e6b80-de27-4098-bb4a-bf8dbf4da405.png)
![group+reroute 06](https://user-images.githubusercontent.com/9657443/236069904-c5a4c79b-c78d-430c-a0ca-5175fcbbda21.png)
![group+reroute 07](https://user-images.githubusercontent.com/9657443/236069939-18364849-b265-46b6-a169-74d54782afc2.png)

end workflow: 
[group+reroute 20230503-02.zip](https://github.com/pythongosssss/ComfyUI/files/11391808/group%2Breroute.20230503-02.zip)

As far as I can tell, the first group node isn't removed when it is converted back to nodes. It can be moved and accepts connections. When converting to nodes again, the resulting nodes are still unconnected from their reroutes. The group-node still exists and can be converted again, though further conversions result in the nodes being removed and replaced in a different spot.

**Comment by wyrde** [comment]
will mess with it more after I get some sleeps

**Comment by wyrde** [comment]
btw, this is on the group+rerouteprimitive branch

**Comment by pythongosssss** [comment]
![image](https://user-images.githubusercontent.com/125205205/236311711-73d4f499-9b35-42eb-9623-953688f26080.png)

Working on this... looks like an issue with primitive -> reroute -> reroute -> group node
